import { useState } from 'react'
import { BrainCircuit, Loader2 } from 'lucide-react'
import PlanCard from './PlanCard'
import { toClock } from '../data/mockEngine'

const PRESETS = [
  {
    id: 'match_rain', label: '⚽ Qarabağ FK Match + Rain (Tofiq Bəhramov)',
    text: 'Qarabağ FK vs Neftçi league match tonight at 20:00 at Tofiq Bahramov Stadium, about 29,000 fans expected. Weather service: heavy rain from 17:00 until midnight, 9°C. Road police warn of slow traffic on Neftchilar Avenue.',
  },
  {
    id: 'school_rush', label: '🎒 Sept 15 School Rush (City-wide Gridlock)',
    text: 'September 15: first day of the school year across Azerbaijan. Roughly 1.5 million pupils and parents travelling between 07:30 and 09:00. Traffic police expect gridlock in Narimanov, Nizami, Khatai and Yasamal. Dry weather, 24°C.',
  },
  {
    id: 'jan20', label: "🕯️ Jan 20 Martyrs' Lane Commemoration",
    text: "January 20, National Mourning Day. Tens of thousands of residents will walk to Martyrs' Lane (Shehidler Xiyabani) and Parliament Avenue from 09:00 to 13:00 to pay respects. Roads near Narimanov will be partially closed. Cold, 5°C, light drizzle.",
  },
  {
    id: 'tbilisi_repairs', label: '🚧 Tbilisi Avenue Emergency Road Repairs',
    text: 'Local news: emergency repairs on Tbilisi Avenue, two of four lanes closed in both directions for the next 5 days, starting Monday. Buses are being diverted via parallel streets, expect delays in the Nizami and Elmlar Akademiyasi area during rush hours.',
  },
]

// Manual mode: a dispatcher pastes a headline or notice. (Autopilot is the main flow.)
export default function AIDispatchPanel({ sim }) {
  const [text, setText] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [result, setResult] = useState(null)
  const [deployed, setDeployed] = useState(false)

  const analyze = async (input, presetId) => {
    const body = (input ?? text).trim()
    if (body.length < 5) { setError('Paste a headline, notice or forecast first.'); return }
    setLoading(true); setError(''); setResult(null); setDeployed(false)
    try {
      const res = await fetch('/api/predict-dispatch', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ text: body, presetId, simTime: toClock(sim.t) }),
      })
      const json = await res.json().catch(() => ({}))
      if (!res.ok) throw new Error(json.error || 'Request failed')
      setResult(json)
    } catch (e) {
      setError(e.message === 'Failed to fetch' ? 'Cannot reach the MoveX API. Start it with npm run dev.' : e.message)
    } finally {
      setLoading(false)
    }
  }

  const runPreset = (p) => { setText(p.text); analyze(p.text, p.id) }

  return (
    <div>
      <div className="grid gap-1.5">
        {PRESETS.map((p) => (
          <button key={p.id} disabled={loading} onClick={() => runPreset(p)}
            className="rounded-lg bg-slate-800 px-3 py-2 text-left text-xs font-medium text-slate-100 ring-1 ring-slate-700 transition hover:bg-indigo-600/30 hover:ring-indigo-400 disabled:opacity-50">
            {p.label}
          </button>
        ))}
      </div>
      <textarea value={text} onChange={(e) => setText(e.target.value)} rows={3} maxLength={3000}
        placeholder="Or paste a news headline, official notice or weather forecast…"
        className="mt-3 w-full resize-none rounded-lg border border-slate-600 bg-slate-900 p-2.5 text-xs text-slate-100 placeholder:text-slate-500 focus:border-indigo-400 focus:outline-none" />
      <button onClick={() => analyze()} disabled={loading}
        className="mt-2 flex w-full items-center justify-center gap-2 rounded-lg bg-indigo-600 py-2 text-sm font-semibold text-white transition hover:bg-indigo-500 disabled:opacity-60">
        {loading ? <><Loader2 className="h-4 w-4 animate-spin" /> Analyzing…</> : <><BrainCircuit className="h-4 w-4" /> Analyze &amp; Generate Dispatch Plan</>}
      </button>
      {error && <p className="mt-2 rounded-lg bg-red-500/10 p-2 text-xs text-red-300">{error}</p>}
      {result?.plan && (
        <div className="mt-3">
          <PlanCard
            plan={result.plan}
            deployed={deployed}
            onDeploy={() => { sim.deployPlan(result.plan.recommended_dispatch, result.plan.scenario_title); setDeployed(true) }}
            offline={result.source !== 'openai'}
            footer={result.source === 'openai' ? `Generated by ${result.model}` : 'Offline fallback plan (AI service unreachable)'}
          />
        </div>
      )}
    </div>
  )
}
